import express from "express";
import cors from "cors";
import dotenv from "dotenv";
import OpenAI from "openai";

dotenv.config();

const app = express();
app.use(cors());
app.use(express.json());

// OpenAI client
const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

// Health check (Render + browser test)
app.get("/", (req, res) => {
  res.json({ status: "AI Text Humanizer API is running" });
});

// Humanizer API (ONLY rewritten text, no questions)
app.post("/humanize", async (req, res) => {
  try {
    const { text } = req.body;

    if (!text || text.trim() === "") {
      return res.status(400).json({ error: "Text is required" });
    }

    const response = await openai.responses.create({
      model: "gpt-4.1-mini",
      input: text,
      instructions:
        You are a professional human content editor.

Your task is to rewrite the given text so it sounds completely human-written.

Rules:
- Keep the original meaning and intent unchanged
- Use natural, conversational language
- Mix short and long sentences organically
- Avoid robotic, formal, or repetitive AI-style phrasing
- Improve flow and readability without over-polishing
- Do not add new information or remove important details
- Do not ask questions or add explanations
- Return ONLY the rewritten text

Rewrite the text below:
 ,
      temperature: 0.9
    });

    // Safe extraction
    let humanizedText = "";

    if (response.output_text) {
      humanizedText = response.output_text;
    } else if (
      response.output &&
      response.output[0] &&
      response.output[0].content &&
      response.output[0].content[0] &&
      response.output[0].content[0].text
    ) {
      humanizedText = response.output[0].content[0].text;
    }

    if (!humanizedText) {
      return res.status(500).json({
        error: "No text generated by OpenAI",
      });
    }

    res.json({
      success: true,
      humanized_text: humanizedText,
    });
  } catch (error) {
    console.error("OPENAI ERROR:", error.message);
    res.status(500).json({
      error: "Humanization failed",
      details: error.message,
    });
  }
});

// IMPORTANT: Render needs dynamic PORT + 0.0.0.0
const PORT = process.env.PORT || 3000;
app.listen(PORT, "0.0.0.0", () => {
  console.log(`Server running on port ${PORT}`);
});
